# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '妙汇_电商_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 妙汇_电商_Swift

  target '妙汇_电商_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '妙汇_电商_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'SnapKit'
end
